services:
  # Frontend container
  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    environment:
      - API_BASE_URL_SERVER=${API_BASE_URL_SERVER}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  # Backend API container
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    depends_on:
      - mongo
    restart: unless-stopped

  # MongoDB container
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

# Define volumes for persistent data
volumes:
  mongo-data:
